module.exports = {
    apps: [
        {
            name: "pm2-view",
            script: "node",
            args: "node_modules/.bin/vite preview --host 0.0.0.0 --port 5179",
            cwd: __dirname,
            instances: 1,
            autorestart: true,
            watch: false,
            max_memory_restart: "500M",
            env: {
                NODE_ENV: "production",
                PORT: "5179",
                HOST: "0.0.0.0",
                ORIGIN: "http://localhost:5179",
                BODY_SIZE_LIMIT: "Infinity",
            },
            env_development: {
                NODE_ENV: "development",
                PORT: "5179",
                BETTER_AUTH_URL: "http://localhost:5179",
            },
            error_file: "./logs/pm2-view-error.log",
            out_file: "./logs/pm2-view-out.log",
            merge_logs: true,
            log_date_format: "YYYY-MM-DD HH:mm:ss Z",
            min_uptime: "10s",
            max_restarts: 10,
            restart_delay: 2000,
            wait_ready: true,
            kill_timeout: 5000,
            listen_timeout: 10000,
        },
        {
            name: "pm2-view-dev",
            script: "pnpm",
            args: "dev -- --host 0.0.0.0",
            cwd: __dirname,
            instances: 1,
            autorestart: false,
            watch: true,
            ignore_watch: ["node_modules", ".svelte-kit", "logs", ".env"],
            max_memory_restart: "1G",
            env: {
                NODE_ENV: "development",
                PORT: "5179",
                BETTER_AUTH_URL: "http://localhost:5179",
            },
            error_file: "./logs/pm2-view-dev-error.log",
            out_file: "./logs/pm2-view-dev-out.log",
            merge_logs: true,
            log_date_format: "YYYY-MM-DD HH:mm:ss Z",
        },
    ],
};
